---

variables:
  CI_EL9: "yes"

include:
  - project: 'dpres/gitlab-ci-pipeline'
    ref: TPASPKT-1054
    file:
      - '/pipeline/common.yml'
      - '/pipeline/fddps.yml'
      - '/pipeline/kppas.yml'
      - '/pipeline/sapa.yml'
